services:
    #################################################################
    ## Controllers as service - autowire
    ## Be careful about this syntax
    #################################################################

    Lucca\Bundle\SecurityBundle\Controller\:
        resource: '../../Controller/'
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]

    #################################################################
    ## Authenticator
    #################################################################

    ## Authenticator - User authenticator to manage login action
    lucca.security.authenticator.simple:
        class: Lucca\Bundle\SecurityBundle\Authenticator\SimpleAuthenticator
        decoration_inner_name: "lucca.admin.authenticator"
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router.default"
            - "@security.user_password_hasher"
            - "@lucca.security.manager.login_attempt"
            - '@Lucca\Bundle\AdherentBundle\Finder\AdherentFinder'
            - '@Lucca\Bundle\DepartmentBundle\Service\UserDepartmentResolver'
            - '@parameter_bag'
            - '@security.login_throttling.main.limiter'
            - '%env(DEFAULT_URL_AFTER_LOGIN)%'
            - '%env(DEFAULT_ADMIN_URL_AFTER_LOGIN)%'

    ## Authenticator - ProConnect authenticator to manage login action
    lucca.security.authenticator.proconnect:
        class: Lucca\Bundle\SecurityBundle\Authenticator\ProconnectAuthenticator
        decoration_inner_name: "lucca.admin.authenticator"
        public: true
        arguments:
            - '@http_client'
            - '@router.default'
            - '@security.user.provider.concrete.lucca_user_provider'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
            - '@Lucca\Bundle\DepartmentBundle\Service\UserDepartmentResolver'
            - '%env(DEFAULT_URL_AFTER_LOGIN)%'
            - '%env(DEFAULT_ADMIN_URL_AFTER_LOGIN)%'
            - '%env(PROCONNECT_AUTH_URL)%'
            - '%env(PROCONNECT_CALLBACK_URL)%'
            - '%env(PROCONNECT_CLIENT_ID)%'
            - '%env(PROCONNECT_CLIENT_SECRET)%'

    #################################################################
    ## Security
    #################################################################

    ## Listen every request - accept request if no failure LoginAttempt
    lucca.security.request_listener:
        class: Lucca\Bundle\SecurityBundle\EventListener\RequestListener
        arguments:
            - "@parameter_bag"
            - "@doctrine.orm.entity_manager"
            - "@router.default"
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    ## Manager - LoginAttempt
    Lucca\Bundle\SecurityBundle\Manager\LoginAttemptManager:
        autowire: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@parameter_bag"

    ## Alias - UserManager
    lucca.security.manager.login_attempt: '@Lucca\Bundle\SecurityBundle\Manager\LoginAttemptManager'

    #################################################################
    ## Access denied listener
    #################################################################

    ## Manager - LoginAttempt
    lucca.security.accessdenied_listener:
        class: Lucca\Bundle\SecurityBundle\EventListener\AccessDeniedHandler
        tags:
            - { name: kernel.event_listener, event: kernel.response }
