# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: true
    fragments: { path: /_fragment }

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        storage_factory_id: session.storage.factory.native
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        gc_maxlifetime: 1440
        # gc_probability/ gc_divisor = 1/100 => 1% of requests will trigger the garbage collector
        gc_probability: 1
        gc_divisor: 1
    
    #esi: true
    #fragments: true
    php_errors:
        log: true
        
    ## Enable setting to work and store it in cache
    cache:
        pools:
            setting.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 0

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
            name: MOCKSESSION
        profiler:
            collect: false
