# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: true
    fragments: { path: /_fragment }

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        storage_factory_id: session.storage.factory.native
#        handler_id: Lucca\Bundle\CoreBundle\Session\CustomPdoSessionHandler
        handler_id: null
#        save_path: 'mysql:host=%env(MYSQL_HOST)%;port=%env(MYSQL_PORT)%;dbname=%env(MYSQL_DATABASE)%'
#        cookie_domain: '%env(COOKIE_DOMAIN)%'
        cookie_path: /
        cookie_secure: auto
        cookie_samesite: lax
        gc_maxlifetime: 43200 # 12 hours
        cookie_lifetime: 43200 # 12 hours
        cookie_httponly: true
        # gc_probability/ gc_divisor = 1/100 => 1% of requests will trigger the garbage collector
        gc_probability: 1
        gc_divisor: 100 # 1% of requests will trigger the garbage collector
    
    #esi: true
    #fragments: true
    php_errors:
        log: true
        
    ## Enable setting to work and store it in cache
    cache:
        pools:
            setting.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 0

    # the IP address (or range) of your proxy
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    # trust *all* "X-Forwarded-*" headers
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix', 'forwarded']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
            name: MOCKSESSION
        profiler:
            collect: false
