###################
# Mail configuration
# Override conf for dev environment
#
# @doc https://symfony.com/doc/current/mailer.html
###################
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
