monolog:
    # Create specific channel for authentication logs
    channels: [ "authentication" ]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

            authentication :
                # log all messages (since debug is the lowest level)
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%env(AUTHENTICATION_LOG)%'
                channels: [ "authentication" ]

when@test:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event" ]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console" ]

            authentication:
                # log all messages (since debug is the lowest level)
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%env(AUTHENTICATION_LOG)%'
                channels: [ "authentication" ]

when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event", "!deprecation", "!php" ]
                max_files: "%env(MAX_ROTATING_FILES)%"
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console" ]

            authentication:
                # log all messages (since debug is the lowest level)
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%env(AUTHENTICATION_LOG)%'
                channels: [ "authentication" ]
