# LuccaModelBundle Routing - Admin
lucca_model_bundle_admin:
    resource: "@LuccaModelBundle/Controller/Admin"
    type:     attribute
    prefix:   /{dep_code}/back-office

# LuccaModelBundle Routing - ByMargin
lucca_model_bundle_by_margin:
    resource: "@LuccaModelBundle/Controller/ByMargin"
    type:     attribute
    prefix:   /{dep_code}/back-office

# LuccaModelBundle Routing - Printing
lucca_minute_bundle_printing:
    resource: "@LuccaModelBundle/Controller/Printing"
    type:     attribute
    prefix:   /{dep_code}/back-office
