services:
    ## Manager - Model Manager
    lucca.manager.model:
        class: Lucca\Bundle\ModelBundle\Manager\ModelManager
        arguments:
            - "@doctrine.orm.entity_manager"
            -
    ## Finder - Model Finder
    lucca.finder.model:
        class: Lucca\Bundle\ModelBundle\Service\ModelFinder
        arguments:
            - "@doctrine.orm.entity_manager"

    ## Manager - Page Manager
    lucca.manager.model.page:
        class: Lucca\Bundle\ModelBundle\Manager\PageManager
        arguments:
            - "@request_stack"

    ## Printer - Model
    lucca.utils.printer.model.page:
        class: Lucca\Bundle\ModelBundle\Printer\PagePrinter
        arguments:
            - "@twig"
            - '@translator'
            - '@?'
