# LuccaUserBundle Routing
lucca_user_bundle:
    resource: "@LuccaUserBundle/Controller/Admin"
    type:     attribute
    prefix:   /back-office

lucca_user_bundle_myProfile:
    resource: "@LuccaUserBundle/Controller/MyProfile"
    type:     attribute
    prefix:   /back-office