## FOSUserBundle Routing
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /back-office/profile
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /back-office/profile
#
#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /back-office/group

# LuccaUserBundle Routing
lucca_user_bundle:
    resource: "@LuccaUserBundle/Controller/Admin"
    type:     attribute
    prefix:   /back-office
