services:
    #################################################################
    ## Manager
    #################################################################
    ## Manager - Page
    lucca.manager.page:
        class: Lucca\Bundle\ContentBundle\Manager\PageManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@lucca.utils.canonalizer"
