# LuccaMinuteBundle Routing
lucca_minute_bundle_admin:
    resource: "@LuccaMinuteBundle/Controller/Admin"
    type:     annotation
    prefix:   /back-office

# LuccaMinuteBundle Routing - Documents
lucca_minute_bundle_document:
    resource: "@LuccaMinuteBundle/Controller/Document"
    type:     annotation
    prefix:   /back-office