# LuccaDecisionBundle Routing
lucca_minute_bundle_admin:
    resource: "@LuccaDecisionBundle/Controller/Admin"
    type:     attribute
    prefix:   /{dep_code}/back-office

# LuccaDecisionBundle Routing - Documents
lucca_minute_bundle_document:
    resource: "@LuccaDecisionBundle/Controller/Document"
    type:     attribute
    prefix:   /{dep_code}/back-office