#######################################
## Lucca
#######################################

LuccaAdherentBundle:
    resource: "@LuccaAdherentBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaChecklistBundle:
    resource: "@LuccaChecklistBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaContentBundle:
    resource: "@LuccaContentBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaCoreBundle:
    resource: "@LuccaCoreBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaDecisionBundle:
    resource: "@LuccaDecisionBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaDepartmentBundle:
    resource: "@LuccaDepartmentBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaFolderBundle:
    resource: "@LuccaFolderBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaLogBundle:
    resource: "@LuccaLogBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaMediaBundle:
    resource: "@LuccaMediaBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaMinuteBundle:
    resource: "@LuccaMinuteBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaModelBundle:
    resource: "@LuccaModelBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaParameterBundle:
    resource: "@LuccaParameterBundle/Resources/config/routing.yaml"
    prefix: /

LuccaSecurityBundle:
    resource: "@LuccaSecurityBundle/Resources/config/routing.yaml"
    prefix:   /


LuccaSettingBundle:
    resource: "@LuccaSettingBundle/Resources/config/routing.yaml"
    prefix:   /

LuccaUserBundle:
    resource: "@LuccaUserBundle/Resources/config/routing.yaml"
    prefix:   /
