# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # Store env var in parameters to make it accessible from routing.yml files
    locale: "%env(APP_LOCALE)%"
    locales_authorized: "%env(APP_LOCALES_AUTHORIZED)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Lucca\:
        resource: '../src/Lucca'
        exclude:
            - '../src/Lucca/*/DependencyInjection/'
            - '../src/Lucca/*/Entity/'
            - '../src/Lucca/*/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Lucca\Bundle\:
        resource: '../src/Lucca/*/Controller/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

#    Lucca\Bundle\CoreBundle\Session\CustomPdoSessionHandler:
#        arguments:
#            - '@request_stack'
#            - '@pdo'
#            - { db_table: lucca_sessions }
#            # Autres paramètres nécessaires pour le PdoSessionHandler
#        public: false
#
#    pdo:
#        class: PDO
#        arguments:
#            - 'mysql:host=%env(MYSQL_HOST)%;port=%env(MYSQL_PORT)%;dbname=%env(MYSQL_DATABASE)%'
#            - '%env(MYSQL_USER)%'
#            - '%env(MYSQL_PASSWORD)%'
#        calls:
#            - [ setAttribute, [ 3, 2 ] ] # PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION
