# LuccaParameterBundle parameters
parameters:
    path.lucca: "%kernel.project_dir%/../../lucca.doc/"
    path.import: "%path.lucca%/importFile/"
    path.historic: "%path.lucca%/historic/"

    file.town: "town.csv"
    file.intercommunal: "intercommunal.csv"
    file.partner: "partner.csv"
    file.service: "service.csv"
    file.tribunal: "tribunal.csv"

services:
