services:
    Lucca\Bundle\DepartmentBundle\EventListener\DoctrineFilterListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Lucca\Bundle\DepartmentBundle\Service\UserDepartmentResolver'
            - '@request_stack'
