services:
    Lucca\Bundle\DepartmentBundle\EventListener\DoctrineFilterListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments:
          [ '@request_stack', '@doctrine.orm.entity_manager' ]
