services:
    #################################################################
    ## Twig
    #################################################################
    
    ## Override Twig -- Assets function with a specific lucca version
    Lucca\Bundle\CoreBundle\Asset\VersionStrategy\NumberVersionStrategy:
        public: false
        arguments:
            - "%env(LUCCA_STRATEGY_ASSET_VERSION)%"
            - "%env(LUCCA_STRATEGY_ASSET_FORCE_REFRESH)%"

    #################################################################
    ## Listener
    #################################################################

    ## Listener for create entity
    lucca.listener.entity_persist:
        class: Lucca\Bundle\CoreBundle\EventListener\EntityPersistListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ## Listener for update entity
    lucca.listener.entity_update:
        class: Lucca\Bundle\CoreBundle\EventListener\EntityUpdateListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    lucca.listener.router:
        class: Lucca\Bundle\CoreBundle\EventListener\RouterListener
        tags:
            - { name: kernel.event_subscriber }
        autowire: true