## LuccaMediaBundle
lucca_media_bundle:
    resource: "@LuccaMediaBundle/Controller"
    type: attribute
    prefix: /

## LuccaMediaBundle Admin
lucca_media_bundle_admin:
    resource: "@LuccaMediaBundle/Controller/Admin"
    type: attribute
    prefix: /{dep_code}/back-office

## LuccaMediaBundle Gallery
lucca_media_bundle_gallery:
    resource: "@LuccaMediaBundle/Controller/Gallery"
    type: attribute
    prefix: /{dep_code}/back-office

## LuccaMediaBundle API
lucca_media_bundle_api:
    resource: "@LuccaMediaBundle/Controller/Api"
    type: attribute
    prefix: /{dep_code}/back-office/api
